apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aether

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: project-aether
  app.kubernetes.io/managed-by: kustomize
